spring.application.name=codedock-backend


spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration,\
org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration,\
org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration,\
org.springframework.boot.autoconfigure.security.oauth2.resource.reactive.ReactiveOAuth2ResourceServerAutoConfiguration


# Logging levels
logging.level.root=INFO
logging.level.com.example.codedockbackend=DEBUG
logging.pattern.level=%5p [%X{traceId}]


# Log file output (optional)
logging.file.name=/app/logs/app.log

# Disable Tomcat access logs (we use our own RequestResponseLoggingFilter)
server.tomcat.accesslog.enabled=false
spring.mvc.log-request-details=false
spring.mvc.servlet.path=/api

# --------------------------
# Database Configuration
# --------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/codedock
spring.datasource.username=postgres
spring.datasource.password=abhi

# --------------------------
# JPA / Hibernate
# --------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# PostgreSQL dialect optional (Hibernate auto-detects)
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --------------------------
# Server
# --------------------------
server.port=8080


# ===============================
# JWT Configuration
# ===============================
spring.config.import=optional:file:.env
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kartiksantwani5@gmail.com
spring.mail.password=ohdn ozni clqz fwgs
#spring.mail.password=abcdefghijklmnop
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Postgress 16
    



