spring.application.name=codedock-backend

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Logging levels
logging.level.root=INFO
logging.level.com.example.codedockbackend=DEBUG
logging.pattern.level=%5p [%X{traceId}]


# Log file output (optional)
logging.file.name=/app/logs/app.log

# Disable Tomcat access logs (we use our own RequestResponseLoggingFilter)
server.tomcat.accesslog.enabled=false

spring.mvc.log-request-details=false

spring.mvc.servlet.path=/api




